In [1]:
# numpy learning
!pip install numpy 

In [2]:
import numpy as np 

In [3]:
arr1 = np.array([1,2,3,4,4,5,6,88,56])
print(arr1)

[ 1  2  3  4  4  5  6 88 56]


In [4]:
arr = arr1.reshape(3,3)
print(arr)

[[ 1  2  3]
 [ 4  4  5]
 [ 6 88 56]]


In [5]:
arr2 = arr1[arr1%2==0]

In [6]:
arr2

array([ 2,  4,  4,  6, 88, 56])

In [15]:
np.arange(1,10,2).reshape(5,1)

array([[1],
       [3],
       [5],
       [7],
       [9]])

In [20]:
np.arange(1,10,1).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(np.sqrt(arr))
print(np.std(arr))
print(np.mean(arr))
print(np.sum(arr))
print(np.min(arr))
print(np.max(arr))
print(np.var(arr))
print(np.argmax(arr))
print(np.argmin(arr))
print(np.percentile(arr,50))
print(np.log(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.cos(arr))
print(np.tan(arr))


[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.        ]
2.581988897471611
5.0
45
1
9
6.666666666666667
8
0
5.0
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501 -0.29100619
  0.87144798 -6.79971146 -0.45231566]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]
[1 2 3 4 5 6 7 8 9 1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]]
[1 2 3 4 5 6 7 8 9 1 2 3 4 5 6 7 8 9]
[array([1, 2, 3]), array([4, 5,

In [ ]:
print(np.round(arr))
print(np.floor(arr))
print(np.ceil(arr))
print(np.unique(arr))
print(np.sort(arr))
print(np.flip(arr))
print(np.concatenate((arr,arr)))
print(np.vstack((arr,arr)))
print(np.hstack((arr,arr)))
print(np.split(arr,3))
print(np.copy(arr))
print(np.where(arr>5))

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]
[[1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]]
[1 2 3 4 5 6 7 8 9 1 2 3 4 5 6 7 8 9]
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
[1 2 3 4 5 6 7 8 9]
(array([5, 6, 7, 8]),)


In [37]:
arr = np.array([[1,2,3],[4.2,5.2,6.6],[70.5,8.6,9]])
print(np.round(arr))
print(np.flip(arr))

[[ 1.  2.  3.]
 [ 4.  5.  7.]
 [70.  9.  9.]]
[[ 9.   8.6 70.5]
 [ 6.6  5.2  4.2]
 [ 3.   2.   1. ]]


In [42]:
arr = np.array([1,2,3,4,5,6,7,4,4,4,4,4,4,4,4,43,3,9])
uni,count=np.unique(arr,return_counts=True)
print(uni)
print(count)

[ 1  2  3  4  5  6  7  9 43]
[1 1 2 9 1 1 1 1 1]


In [44]:
### Learing the hstack and vstack functions

In [45]:
arr = np.array([1,2,3,4,5,6,7,7,8])
print(np.hstack((arr,arr)))

[1 2 3 4 5 6 7 7 8 1 2 3 4 5 6 7 7 8]


In [46]:
print(np.vstack((arr,arr)))

[[1 2 3 4 5 6 7 7 8]
 [1 2 3 4 5 6 7 7 8]]


In [47]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(np.split(arr, 3))
# Output: [array([1, 2]), array([3, 4]), array([5, 6])]

[array([1, 2]), array([3, 4]), array([5, 6])]


In [48]:
b = np.copy(arr)
b[0] = 99
print(arr)  # [1 3 5 7 9] → original unchanged
print(b)    # [99 3 5 7 9]

[1 2 3 4 5 6]
[99  2  3  4  5  6]
