# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [8]:
import numpy as np 
arr = np.random.randint(1,21,size=(5,5))
print(arr)
arr[::,3]=1
print(arr)

[[ 6  3  8  1  8]
 [15 10  7 16 15]
 [ 2 16  3 17  4]
 [ 9 20 13 19  3]
 [19  6  7 12  5]]
[[ 6  3  8  1  8]
 [15 10  7  1 15]
 [ 2 16  3  1  4]
 [ 9 20 13  1  3]
 [19  6  7  1  5]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [ ]:
import numpy as np
arr = np.random.randint(1,16,size=(4,4))
print(arr)
for i in range(0,len(arr)):
  for j in range(arr.shape[1]):
    if i==j:
      arr[i][j]=0
print(arr)

np.fill_diagonal(arr, 0) 

[[ 8 14  4  1]
 [ 9  8 11  1]
 [ 1 14 11  4]
 [13  5  9 13]]
[[ 0 14  4  1]
 [ 9  0 11  1]
 [ 1 14  0  4]
 [13  5  9  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [34]:
import numpy as np 
arr = np.random.randint(1,36,size=(6,6))
print(arr)
arr.flat[::5]=0
print(arr)


[[25 20 13  6 25  2]
 [21 15  8 32 24  3]
 [27 10 11 28 34 34]
 [ 6 30 20 34 19 20]
 [28 12 21 13 30  7]
 [12 14 16  3 35 18]]
[[ 0 20 13  6 25  0]
 [21 15  8 32  0  3]
 [27 10 11  0 34 34]
 [ 6 30  0 34 19 20]
 [28  0 21 13 30  7]
 [ 0 14 16  3 35  0]]


2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [18]:
import numpy as np 
arr= np.random.randint(1,50,size=(5,5))
print(arr)
rows ,cols = np.indices(arr.shape)
data = arr[(rows==0)|(cols==0)]
data

[[17 39 12  8 38]
 [ 4  1 49  2 40]
 [41 41 32 38 48]
 [25 36 10  4 36]
 [ 3 36 44 43  7]]


array([17, 39, 12,  8, 38,  4, 41, 25,  3], dtype=int32)

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [20]:
arr1 = np.random.randint(1,10,size=(3,4))
arr2 = np.random.randint(1,10,size=(3,4))
print(arr1)
print(arr2)
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)


[[5 7 4 3]
 [6 5 6 6]
 [5 4 1 9]]
[[8 1 4 8]
 [6 8 5 7]
 [8 6 8 6]]
[[13  8  8 11]
 [12 13 11 13]
 [13 10  9 15]]
[[-3  6  0 -5]
 [ 0 -3  1 -1]
 [-3 -2 -7  3]]
[[40  7 16 24]
 [36 40 30 42]
 [40 24  8 54]]
[[0.625      7.         1.         0.375     ]
 [1.         0.625      1.2        0.85714286]
 [0.625      0.66666667 0.125      1.5       ]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [22]:
arr = np.random.randint(1,16,size= (4,4))
print(arr)

rowSum = np.sum(arr, axis=1)
colSum = np.sum(arr, axis=0)
print("Row sums:", rowSum)
print("Column sums:", colSum)

[[ 8 11  4  1]
 [13  1 10  3]
 [15  3  6 13]
 [11  8  4  6]]
Row sums: [24 27 37 29]
Column sums: [47 23 24 23]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [25]:
arr=np.random.randint(1,21,size=(5,5))
print(np.mean(arr))  # mean of all elements
print(np.mean(arr, axis=0))  # mean of each column
print(np.mean(arr, axis=1))  # mean of each row
print(np.median(arr))  # median of all elements
print(np.median(arr, axis=0))  # median of each column
print(np.median(arr, axis=1))  # median of each row
print(np.std(arr))  # standard deviation of all elements
print(np.std(arr, axis=0))  # standard deviation of each column
print(np.std(arr, axis=1))  # standard deviation of each row
print(np.var(arr))  # variance of all elements
print(np.var(arr, axis=0))  # variance of each column
print(np.var(arr, axis=1))  # variance of each row

11.6
[16.   9.2 14.2  7.6 11. ]
[ 7.4 15.4 11.4 10.6 13.2]
13.0
[15.  9. 13.  8. 15.]
[ 9. 17. 10. 11. 15.]
5.642694391866354
[2.52982213 5.38144962 4.11825206 3.72021505 6.69328021]
[5.42586399 4.45421149 4.02988834 3.72021505 6.64529909]
31.84
[ 6.4  28.96 16.96 13.84 44.8 ]
[29.44 19.84 16.24 13.84 44.16]


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.

2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.