# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [8]:
import numpy as np 
arr = np.random.randint(1,21,size=(5,5))
print(arr)
arr[::,3]=1
print(arr)

[[ 6  3  8  1  8]
 [15 10  7 16 15]
 [ 2 16  3 17  4]
 [ 9 20 13 19  3]
 [19  6  7 12  5]]
[[ 6  3  8  1  8]
 [15 10  7  1 15]
 [ 2 16  3  1  4]
 [ 9 20 13  1  3]
 [19  6  7  1  5]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [ ]:
import numpy as np
arr = np.random.randint(1,16,size=(4,4))
print(arr)
for i in range(0,len(arr)):
  for j in range(arr.shape[1]):
    if i==j:
      arr[i][j]=0
print(arr)

np.fill_diagonal(arr, 0) 

[[ 8 14  4  1]
 [ 9  8 11  1]
 [ 1 14 11  4]
 [13  5  9 13]]
[[ 0 14  4  1]
 [ 9  0 11  1]
 [ 1 14  0  4]
 [13  5  9  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [34]:
import numpy as np 
arr = np.random.randint(1,36,size=(6,6))
print(arr)
arr.flat[::5]=0
print(arr)


[[25 20 13  6 25  2]
 [21 15  8 32 24  3]
 [27 10 11 28 34 34]
 [ 6 30 20 34 19 20]
 [28 12 21 13 30  7]
 [12 14 16  3 35 18]]
[[ 0 20 13  6 25  0]
 [21 15  8 32  0  3]
 [27 10 11  0 34 34]
 [ 6 30  0 34 19 20]
 [28  0 21 13 30  7]
 [ 0 14 16  3 35  0]]


2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.

2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.